[workspace]
members = [
    "nrf5x-prx",
    "nrf5x-ptx",
    "dwm1001-ptx",
    "dwm1001-prx",
]

[profile.dev]
opt-level = "s"

[profile.release]
opt-level = "s"
debug = true
lto = true
codegen-units = 1
